Change the target of the compilation command (o=parse=frama-c or n=total=framac+eacsl) in 02-ringbufindex.csc
currently it segfaults (probably because the mt cooja library calls main() instead of prepare_memory())

it may be necessary to launch cooja graphically at least one time (??
for the registration of Contiki cooja plugins ?!?!?!)

then for n :

cd ~/Info/VESSEDIA/contiki-ng/tools/cooja

cd ~/Info/VESSEDIA/contiki-ng/tests/07-simulation-base
ant -Dbasedir=$HOME/Info/VESSEDIA/contiki-ng/tools/cooja -f $HOME/Info/VESSEDIA/contiki-ng/tools/cooja/build.xml jar_cooja && java -Xshare:on -jar ../../tools/cooja/dist/cooja.jar -nogui=02-ringbufindex.csc -contiki=../.. -random-seed=1

=>

...
Message:frama-c -no-warn-invalid-bool -no-frama-c-stdlib -c11 -cpp-frama-c-compliant -variadic-no-translation -machdep gcc_x86_32 -e-acsl-prepare -rte -warn-signed-overflow -warn-signed-downcast -rte-div -rte-float-to-int -rte-mem -rte-pointer-call -rte-shift -rte-no-trivial-annotations -cpp-extra-args=-I'/usr/lib/jvm/default-java/include' -I'/usr/lib/jvm/default-java/include/linux' -fno-builtin-printf -fPIC -Wall -g -I/usr/local/include -DCLASSNAME=Lib1 -Werror -DCONTIKI=1 -DCONTIKI_TARGET_COOJA=1 -DCONTIKI_TARGET_STRING=\"cooja\" -DPROJECT_CONF_PATH=\"project-conf.h\" -I/usr/lib/jvm/default-java/include -I/usr/lib/jvm/default-java/include/linux -I/usr/local/include -DCLASSNAME=Lib1 -DMAC_CONF_WITH_CSMA=1 -DNETSTACK_CONF_WITH_IPV6=1 -DROUTING_CONF_RPL_LITE=1 -I. -I../../../arch/platform/cooja/. -I../../../arch/platform/cooja/dev -I../../../arch/platform/cooja/lib -I../../../arch/platform/cooja/sys -I../../../arch/platform/cooja/cfs -I../../../arch/platform/cooja/net -I../../../arch -I../../../os/services/unit-test -I../../../os -I../../../os/sys -I../../../os/dev -I../../../os/lib -I../../../os/services -I../../../os -I../../../os/net -I../../../os/net/mac -I../../../os/net/mac/framer -I../../../os/net/routing -I../../../os/storage -I../../../os/net/mac/csma -I../../../os/net/ipv6 -I../../../os/net/routing/rpl-lite -I../../../arch/platform/cooja/ -I../../.. -DCONTIKI_VERSION_STRING=\"Contiki-NG-release/v4.2-185-g6c9895a-dirty\" ../../../arch/platform/cooja/./platform.c ../../../arch/platform/cooja/lib/simEnvChange.c ../../../arch/platform/cooja/sys/cooja_mt.c ../../../arch/platform/cooja/sys/cooja_mtarch.c ../../../arch/platform/cooja/./rtimer-arch.c ../../../os/dev/slip.c ../../../arch/platform/cooja/dev/watchdog.c ../../../arch/platform/cooja/dev/beep.c ../../../arch/platform/cooja/dev/button-sensor.c ../../../arch/platform/cooja/dev/ip.c ../../../arch/platform/cooja/dev/leds-arch.c ../../../arch/platform/cooja/dev/moteid.c ../../../arch/platform/cooja/dev/pir-sensor.c ../../../arch/platform/cooja/dev/rs232.c ../../../arch/platform/cooja/dev/vib-sensor.c ../../../arch/platform/cooja/sys/clock.c ../../../arch/platform/cooja/sys/cooja-log.c ../../../arch/platform/cooja/cfs/cfs-cooja.c ../../../arch/platform/cooja/dev/cooja-radio.c ../../../arch/platform/cooja/dev/eeprom.c ../../../arch/platform/cooja/./slip-arch.c ../../../arch/platform/cooja/int-master.c ../../../os/lib/random.c ../../../os/lib/sensors.c ../../../os/dev/leds.c ../../../os/services/unit-test/example-test.c ../../../os/services/unit-test/unit-test.c ../../../os/contiki-main.c ../../../os/sys/autostart.c ../../../os/sys/stimer.c ../../../os/sys/log.c ../../../os/sys/energest.c ../../../os/sys/etimer.c ../../../os/sys/node-id.c ../../../os/sys/mutex.c ../../../os/sys/ctimer.c ../../../os/sys/compower.c ../../../os/sys/process.c ../../../os/sys/rtimer.c ../../../os/sys/timer.c ../../../os/dev/serial-line.c ../../../os/dev/nullradio.c ../../../os/lib/dbl-circ-list.c ../../../os/lib/crc16.c ../../../os/lib/ifft.c ../../../os/lib/ccm-star.c ../../../os/lib/dbl-list.c ../../../os/lib/ringbufindex.c ../../../os/lib/list.c ../../../os/lib/circular-list.c ../../../os/lib/aes-128.c ../../../os/lib/trickle-timer.c ../../../os/lib/memb.c ../../../os/lib/heapmem.c ../../../os/lib/assert.c ../../../os/lib/ringbuf.c ../../../os/net/queuebuf.c ../../../os/net/nbr-table.c ../../../os/net/packetbuf.c ../../../os/net/netstack.c ../../../os/net/linkaddr.c ../../../os/net/net-debug.c ../../../os/net/link-stats.c ../../../os/net/mac/mac-sequence.c ../../../os/net/mac/mac.c ../../../os/net/mac/framer/frame802154e-ie.c ../../../os/net/mac/framer/framer-802154.c ../../../os/net/mac/framer/nullframer.c ../../../os/net/mac/framer/frame802154.c ../../../os/net/mac/csma/csma-security.c ../../../os/net/mac/csma/anti-replay.c ../../../os/net/mac/csma/csma.c ../../../os/net/mac/csma/csma-output.c ../../../os/net/mac/csma/ccm-star-packetbuf.c ../../../os/net/ipv6/uipbuf.c ../../../os/net/ipv6/uip-icmp6.c ../../../os/net/ipv6/uip-sr.c ../../../os/net/ipv6/uip-ds6.c ../../../os/net/ipv6/uip-packetqueue.c ../../../os/net/ipv6/ip64-addr.c ../../../os/net/ipv6/uip-udp-packet.c ../../../os/net/ipv6/uip-ds6-route.c ../../../os/net/ipv6/psock.c ../../../os/net/ipv6/uip-ds6-nbr.c ../../../os/net/ipv6/tcpip.c ../../../os/net/ipv6/uip6.c ../../../os/net/ipv6/resolv.c ../../../os/net/ipv6/uip-nameserver.c ../../../os/net/ipv6/uip-nd6.c ../../../os/net/ipv6/udp-socket.c ../../../os/net/ipv6/simple-udp.c ../../../os/net/ipv6/sicslowpan.c ../../../os/net/ipv6/uiplib.c ../../../os/net/routing/rpl-lite/rpl-nbr-policy.c ../../../os/net/routing/rpl-lite/rpl-of0.c ../../../os/net/routing/rpl-lite/rpl-neighbor.c ../../../os/net/routing/rpl-lite/rpl-dag.c ../../../os/net/routing/rpl-lite/rpl-timers.c ../../../os/net/routing/rpl-lite/rpl-ext-header.c ../../../os/net/routing/rpl-lite/rpl.c ../../../os/net/routing/rpl-lite/rpl-mrhof.c ../../../os/net/routing/rpl-lite/rpl-icmp6.c ../../../os/net/routing/rpl-lite/rpl-dag-root.c -then -e-acsl -e-acsl-full-mmodel -then-last -print -ocode cooja.total/framac.c
Message:mtype148
Message:cat cooja.total/framac.c ../../../prepare_memory.c ../../../jnimain.c > cooja.total/prepare_framac.c
Message:sed -i -e '665,700{s/^/\/\//g}' cooja.total/prepare_framac.c
Message:sed -i -e 's/typedef char int8_t;/typedef signed char int8_t;/g' cooja.total/prepare_framac.c
Message:gcc -ffunction-sections -fdata-sections -DE_ACSL_SEGMENT_MMODEL -DE_ACSL_STACK_SIZE=32 -DE_ACSL_HEAP_SIZE=128 -std=c99 -m32 -g -O0 -fno-builtin -fno-merge-constants -Wno-attributes -DCONTIKI=1 -DCONTIKI_TARGET_COOJA=1 -DCONTIKI_TARGET_STRING=\"cooja\" -Wno-unused-const-variable -DPROJECT_CONF_PATH=\"project-conf.h\" -I'/usr/lib/jvm/default-java/include' -I'/usr/lib/jvm/default-java/include/linux' -fno-builtin-printf -Wall -g -I/usr/local/include -DCLASSNAME=Lib1 -DMAC_CONF_WITH_CSMA=1 -DNETSTACK_CONF_WITH_IPV6=1 -DROUTING_CONF_RPL_LITE=1  -I. -I../../../arch/platform/cooja/. -I../../../arch/platform/cooja/dev -I../../../arch/platform/cooja/lib -I../../../arch/platform/cooja/sys -I../../../arch/platform/cooja/cfs -I../../../arch/platform/cooja/net -I../../../arch -I../../../os/services/unit-test -I../../../os -I../../../os/sys -I../../../os/dev -I../../../os/lib -I../../../os/services -I../../../os -I../../../os/net -I../../../os/net/mac -I../../../os/net/mac/framer -I../../../os/net/routing -I../../../os/storage -I../../../os/net/mac/csma -I../../../os/net/ipv6 -I../../../os/net/routing/rpl-lite -I../../../arch/platform/cooja/ -I../../.. -DCONTIKI_VERSION_STRING=\"Contiki-NG-release/v4.2-173-ge82159a-dirty\" -MMD -o cooja.total/mtype148.o -c cooja.total/prepare_framac.c
Message:cooja.total/prepare_framac.c: In function 'cfs_open':
Message:cooja.total/prepare_framac.c:5940:8: warning: suggest explicit braces to avoid ambiguous 'else' [-Wparentheses]
Message:     if (f & 2)
Message:        ^
Message:cooja.total/prepare_framac.c: In function 'uip_ds6_get_link_local':
Message:cooja.total/prepare_framac.c:44146:10: warning: suggest explicit braces to avoid ambiguous 'else' [-Wparentheses]
Message:       if (locaddr->isused)
Message:          ^
Message:cooja.total/prepare_framac.c: In function 'uip_ds6_get_global':
Message:cooja.total/prepare_framac.c:44240:10: warning: suggest explicit braces to avoid ambiguous 'else' [-Wparentheses]
Message:       if (locaddr->isused)
Message:          ^
Message:cooja.total/prepare_framac.c: In function 'uip_send':
Message:cooja.total/prepare_framac.c:55675:8: warning: suggest explicit braces to avoid ambiguous 'else' [-Wparentheses]
Message:     if ((void *)data != uip_sappdata)
Message:        ^
Message:cooja.total/prepare_framac.c: In function 'newdata':
Message:cooja.total/prepare_framac.c:58527:39: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
Message:       struct dns_question *question = skip_name(queryptr);
Message:                                       ^
Message:cooja.total/prepare_framac.c: In function 'process_thread_resolv_process':
Message:cooja.total/prepare_framac.c:59892:20: warning: suggest explicit braces to avoid ambiguous 'else' [-Wparentheses]
Message:                 if ((int)uip_flags & 8)
Message:                    ^
Message:cooja.total/prepare_framac.c: In function 'update_state':
Message:cooja.total/prepare_framac.c:75749:7: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
Message:       uip_ds6_nbr_get_ll((uip_ds6_nbr_t const *)ds6_nbr);
Message:       ^
Message:cooja.total/prepare_framac.c: In function 'process_dio_from_current_dag':
Message:cooja.total/prepare_framac.c:79621:6: warning: suggest explicit braces to avoid ambiguous 'else' [-Wparentheses]
Message:   if (tmp_2)
Message:      ^
Message:cooja.total/prepare_framac.c: In function 'handle_dis_timer':
Message:cooja.total/prepare_framac.c:81200:6: warning: suggest explicit braces to avoid ambiguous 'else' [-Wparentheses]
Message:   if (! tmp)
Message:      ^
Message:cooja.total/prepare_framac.c: In function 'get_probing_target':
Message:cooja.total/prepare_framac.c:81796:12: warning: suggest explicit braces to avoid ambiguous 'else' [-Wparentheses]
Message:         if (stats != (struct link_stats const *)0)
Message:            ^
Message:cooja.total/prepare_framac.c: In function 'dio_input':
Message:cooja.total/prepare_framac.c:87728:10: warning: suggest explicit braces to avoid ambiguous 'else' [-Wparentheses]
Message:       if (! ((int)dio.mc.type == 0))
Message:          ^
Message:cooja.total/prepare_framac.c: In function 'rpl_icmp6_dio_output':
Message:cooja.total/prepare_framac.c:89549:6: warning: suggest explicit braces to avoid ambiguous 'else' [-Wparentheses]
Message:   if (! tmp_29)
Message:      ^
Message:cooja.total/prepare_framac.c: In function 'set_global_address':
Message:cooja.total/prepare_framac.c:91466:10: warning: suggest explicit braces to avoid ambiguous 'else' [-Wparentheses]
Message:       if (uip_ds6_if.addr_list[i].isused)
Message:          ^
Message:cooja.total/prepare_framac.c: In function 'mem_stats':
Message:cooja.total/prepare_framac.c:97247:12: warning: implicit declaration of function 'getline' [-Wimplicit-function-declaration]
Message:     while (getline(&line, &size, maps) > 0) {
Message:            ^
Message:cooja.total/prepare_framac.c: At top level:
Message:cc1: warning: unrecognized command line option '-Wno-unused-const-variable'
Message:gcc -ffunction-sections -fdata-sections -DE_ACSL_SEGMENT_MMODEL -DE_ACSL_STACK_SIZE=32 -DE_ACSL_HEAP_SIZE=128 -std=c99 -m32 -g -O0 -fno-builtin -fno-merge-constants -Wno-attributes  -DCONTIKI=1 -DCONTIKI_TARGET_COOJA=1 -DCONTIKI_TARGET_STRING=\"cooja\" -Wno-unused-const-variable -DPROJECT_CONF_PATH=\"project-conf.h\" -I'/usr/lib/jvm/default-java/include' -I'/usr/lib/jvm/default-java/include/linux' -fno-builtin-printf -Wall -g -I/usr/local/include -DCLASSNAME=Lib1 -DMAC_CONF_WITH_CSMA=1 -DNETSTACK_CONF_WITH_IPV6=1 -DROUTING_CONF_RPL_LITE=1  -I. -I../../../arch/platform/cooja/. -I../../../arch/platform/cooja/dev -I../../../arch/platform/cooja/lib -I../../../arch/platform/cooja/sys -I../../../arch/platform/cooja/cfs -I../../../arch/platform/cooja/net -I../../../arch -I../../../os/services/unit-test -I../../../os -I../../../os/sys -I../../../os/dev -I../../../os/lib -I../../../os/services -I../../../os -I../../../os/net -I../../../os/net/mac -I../../../os/net/mac/framer -I../../../os/net/routing -I../../../os/storage -I../../../os/net/mac/csma -I../../../os/net/ipv6 -I../../../os/net/routing/rpl-lite -I../../../arch/platform/cooja/ -I../../.. -DCONTIKI_VERSION_STRING=\"Contiki-NG-release/v4.2-173-ge82159a-dirty\" -MMD -o test-ringbufindex.o -c test-ringbufindex.c
Message:mkdir -p build/cooja/
Message:ar rcf build/cooja/mtype148.a cooja.total/mtype148.o
Message:#mv platform.o build/cooja///mtype148.o
Message:# LOG_PRINTF
Message:#objcopy --redefine-sym printf=log_printf build/cooja///mtype148.o;
Message:objcopy --redefine-sym printf=log_printf test-ringbufindex.o
Message:objcopy --redefine-sym printf=log_printf cooja.total/mtype148.o
Message:objcopy --redefine-sym printf=log_printf build/cooja/mtype148.a
Message:# LOG_PUTS
Message:#objcopy --redefine-sym puts=log_puts build/cooja///mtype148.o;
Message:objcopy --redefine-sym puts=log_puts test-ringbufindex.o
Message:objcopy --redefine-sym puts=log_puts cooja.total/mtype148.o
Message:objcopy --redefine-sym puts=log_puts build/cooja/mtype148.a
Message:# LOG_PUTCHAR
Message:#objcopy --redefine-sym putchar=log_putchar build/cooja///mtype148.o
Message:objcopy --redefine-sym putchar=log_putchar test-ringbufindex.o
Message:objcopy --redefine-sym putchar=log_putchar cooja.total/mtype148.o
Message:objcopy --redefine-sym putchar=log_putchar build/cooja/mtype148.a
Message:gcc -Wl,--gc-sections -ffunction-sections -fdata-sections -DE_ACSL_SEGMENT_MMODEL -DE_ACSL_STACK_SIZE=32 -DE_ACSL_HEAP_SIZE=128 -std=c99 -m32 -g -O0 -fno-builtin -fno-merge-constants -Wall -Wno-long-long -Wno-attributes -Wno-nonnull -Wno-undef -Wno-unused -Wno-unused-function -Wno-unused-result -Wno-unused-value -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-implicit-function-declaration -Wno-empty-body -Wl,-Map=cooja.total/mtype148.map -I/home/jean/local-frama-c/bin/../share/frama-c/e-acsl/ -shared -o cooja.total/mtype148.cooja test-ringbufindex.o build/cooja/mtype148.a /home/jean/local-frama-c/bin/../share/frama-c/e-acsl//e_acsl_rtl.c /home/jean/local-frama-c/bin/../lib/libeacsl-dlmalloc.a /home/jean/local-frama-c/bin/../lib/libeacsl-gmp.a -lm
Message:cp cooja.total/mtype148.cooja test-ringbufindex.cooja
Message:cp cooja.total/mtype148.map build/cooja/
Message:cp test-ringbufindex.cooja build/cooja/mtype148.cooja
Message:#rm test-ringbufindex.o
 INFO [main] (ContikiMoteType.java:406) - Creating core communicator between Java class Lib1 and Contiki library '/home/jean/Info/VESSEDIA/contiki-ng/tests/07-simulation-base/code-ringbufindex/build/cooja/mtype148.cooja'
/home/jean/travail/outils/h: line 7: 10865 Aborted                 (core dumped) java -Xshare:on -jar ../../tools/cooja/dist/cooja.jar -nogui=02-ringbufindex.csc -contiki=../.. -random-seed=1

//////////////////////
but with o, you should get :
//////////////////////

INFO [main] (ContikiMoteType.java:406) - Creating core communicator between Java class Lib1 and Contiki library '/home/jean/Info/VESSEDIA/contiki-ng/tests/07-simulation-base/code-ringbufindex/build/cooja/mtype262.cooja'
 INFO [main] (ContikiMoteType.java:580) - Parsed section at 0x4b020 ( 1300 == 0x514 bytes)
 INFO [main] (ContikiMoteType.java:580) - Parsed section at 0x4b540 ( 84140 == 0x148ac bytes)
 INFO [main] (ContikiMoteType.java:502) - mtype262.cooja: offsetting Cooja mote address space: 0xa0fa0000
 INFO [main] (ContikiMoteType.java:580) - Parsed section at 0xa0feb020 ( 1300 == 0x514 bytes)
 INFO [main] (ContikiMoteType.java:580) - Parsed section at 0xa0feb540 ( 84140 == 0x148ac bytes)
 INFO [main] (ContikiRadio.java:397) - Radio bitrate reconfigured to (kbps): 250.0
 INFO [main] (Cooja.java:1782) - Visualized plugin was not started: class org.contikios.cooja.plugins.SimControl
 INFO [main] (Cooja.java:1782) - Visualized plugin was not started: class org.contikios.cooja.plugins.Visualizer
 INFO [main] (Cooja.java:1782) - Visualized plugin was not started: class org.contikios.cooja.plugins.LogListener
 INFO [main] (Cooja.java:1782) - Visualized plugin was not started: class org.contikios.cooja.plugins.TimeLine
 INFO [main] (Cooja.java:1782) - Visualized plugin was not started: class org.contikios.cooja.plugins.Notes
 INFO [main] (ScriptRunner.java:430) - Test script deactivated
 INFO [main] (LogScriptEngine.java:265) - Script timeout in 10000 ms
 INFO [main] (ScriptRunner.java:387) - Test script activated
 INFO [Thread-2] (Simulation.java:253) - Simulation main loop started, system time: 1553718422949
 INFO [Thread-2] (LogScriptEngine.java:389) - Test script at 5.00%, done in 0.1 sec
 INFO [Thread-1] (LogScriptEngine.java:309) - Test script finished
 INFO [Thread-2] (Simulation.java:312) - Simulation main loop stopped, system time: 1553718423028  Duration: 79 ms Simulated time 549 ms Ratio 6.949367088607595
 INFO [AWT-EventQueue-0] (ScriptRunner.java:430) - Test script deactivated